# Generated by Django 3.2.9 on 2021-11-11 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HiBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('paragraph', models.CharField(max_length=10000)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HiBlog.newsubjects')),
            ],
        ),
    ]
