# Generated by Django 3.2.9 on 2021-11-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HiBlog', '0003_auto_20211114_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('sub_heading', models.CharField(max_length=100, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('paragraph', models.CharField(max_length=10000)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HiBlog.newsubjects')),
            ],
        ),
    ]
