# Generated by Django 3.2.9 on 2021-11-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiBlog', '0004_data_newsubjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='sub_heading',
        ),
    ]
