# Generated by Django 3.2.9 on 2021-11-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiBlog', '0007_data_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='blogimages/'),
        ),
    ]
