# Generated by Django 3.2.9 on 2021-11-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiBlog', '0008_alter_data_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsubjects',
            name='user',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='NewSubjects',
        ),
    ]
